In [135]:
import pandas as pd
import numpy as np

In [136]:
df=pd.read_csv("data/combine_monthly_summary.csv")

In [137]:
df = df[df["Country_Region"].notna()].copy()

In [138]:
# List of known non-country entries in the JHU data
non_countries = [
    "Diamond Princess", "Grand Princess", "MS Zaandam", "Recovered",
    "Holy See", "Summer Olympics 2020", "Winter Olympics 2022", "Kosovo", 
    "West Bank and Gaza", "Burma", "Micronesia",
    "Congo (Kinshasa)", "Congo (Brazzaville)", "Eswatini", "Korea, South",
    "Laos", "North Macedonia", "Timor-Leste", "Palestine",
    "Mainland China", "occupied Palestinian territory"
]

# Filter the dataframe to keep only valid countries
df_cleaned = df[~df["Country_Region"].isin(non_countries)].copy()

In [139]:
df_cleaned = df_cleaned.sort_values(by="Country_Region").reset_index(drop=True)

In [145]:
non_states = [
    "Diamond Princess", "Grand Princess", "MS Zaandam",
    "Repatriated Travellers", "Unassigned",
    "French Guiana", "Greenland", "Hong Kong", "Macau",
    "Guadeloupe", "Martinique", "Faroe Islands", "Gibraltar",
    "Bermuda", "Isle of Man","Recovered"
]

# Drop rows where Province_State is in the non_states list
df_cleaned_2 = df_cleaned[~df_cleaned["Province_State"].isin(non_states)].copy()

In [146]:
df_cleaned_2.to_csv("data/combine_monthly_summary.csv", index= False)

In [148]:
df_cleaned.Country_Region.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antarctica', 'Antigua and Barbuda', 'Argentina', 'Armenia',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba',
       'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Fiji',
       'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Korea, North', 'Kuwait', 'Kyrgyzstan',
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'Norway', 'Oman', 'Pakistan', 'Palau',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Syria', 'Taiwan*', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo',
       'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Tuvalu',
       'US', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [143]:
df_cleaned.shape

(144298, 20)

In [144]:
df.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Date,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Active,Combined_Key,Incidence_Rate,Case-Fatality_Ratio,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,4.0,0.0,0.0,2020-03-31,45001.0,Abbeville,South Carolina,US,2020-03-31 23:43:56,34.223334,-82.461707,4.0,"Abbeville, South Carolina, US",NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,39.0,1.0,0.0,2020-03-31,22001.0,Acadia,Louisiana,US,2020-03-31 23:43:56,30.295065,-92.414197,38.0,"Acadia, Louisiana, US",NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,7.0,0.0,0.0,2020-03-31,51001.0,Accomack,Virginia,US,2020-03-31 23:43:56,37.767072,-75.632346,7.0,"Accomack, Virginia, US",NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,195.0,3.0,0.0,2020-03-31,16001.0,Ada,Idaho,US,2020-03-31 23:43:56,43.452658,-116.241552,192.0,"Ada, Idaho, US",NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,1.0,0.0,0.0,2020-03-31,19001.0,Adair,Iowa,US,2020-03-31 23:43:56,41.330756,-94.471059,1.0,"Adair, Iowa, US",NaN,NaN,NaN,NaN